### ISSUE TITLE
Ryk til gitlab.au.dk/tutor

### ISSUE THREAD

**Issue by Tyilo** [matfystutor/web#139]
Nu når alt andet er på gitlab, ville det give mening at flytte repoerne til gitlab.

Men er det en god ide?

**Comment by Mortal** [comment]
Mener du Gitlab.com eller Gitlab.au.dk? Jeg synes koden til hjemmesiden bør forblive open source, men jeg har ikke holdning til Github.com vs. Gitlab.com.

**Comment by Tyilo** [comment]
Jeg mente nu gitlab.au.dk, men kan godt se at så kræver det at man har en AU bruger.

Desuden så er `tutor` gruppen på gitlab.au.dk "internal", hvilket betyder man ikke kan lave public repos.

**Comment by Mortal** [comment]
Så vidt jeg ved understøtter gitlab.au.dk offentlige repos. Hvis `tutor` orgen på gitlab.au.dk ikke er sat op til at kunne det, kan man vel undersøge om det kan fikses. Jeg ville personligt være ked af at miste muligheden for at følge med i udviklingen, men det er selvfølgelig op til webgruppen om ting skal konsolideres på gitlab.au.dk.

**Comment by tskovlund** [comment]
Jeg kan i hvert fald ikke se nogen grund til at det ikke skal være
offentligt tilgængeligt. Det fungerer godt på GitHub lige nu, og har jo
ligget der længe før vi begyndte at lægge andre ting på gitlab.au.dk. Jeg
kan undersøge, om jeg kan lave et offentligt repository på gitlab.au.dk,
men jeg synes dog,  det kræver bedre argumenter, end at tutorforeningens
andet arbejde ligger dér, for at jeg vil bruge tid på at flytte det.
