### ISSUE TITLE
Sorter kalender efter klokkeslæt hvis dato er den samme

### ISSUE THREAD

**Issue by tskovlund** [matfystutor/web#178]
Det kunne være fedt hvis kalenderen var sorteret helt kronologisk. Lige nu er "Prodekanens tak" efter "4. stormøde" selv om det i virkeligheden foregår lige inden.

<img width="472" alt="Screenshot 2022-06-29 at 14 36 14" src="https://user-images.githubusercontent.com/7204970/176437665-26e5a47f-f641-4657-a8d9-1b5667e7d0a4.png">

**Comment by kandevander** [comment]
Tænker det kan fikses hvis man i views.py for event ændrer:


    def get_queryset(self):
        qs = Event.objects.filter(start_date__year=self.get_year())
        return qs.order_by('start_date')

til:


    def get_queryset(self):
        qs = Event.objects.filter(start_date__year=self.get_year())
        return qs.order_by('start_date', 'start_time')
