### ISSUE TITLE
TutorGroup model skal have år

### ISSUE THREAD

**Issue by sortie** [matfystutor/web#20]
Det ville være bedre hvis at en tutorgruppe har tilknyttet et år, da grupper ikke altid deles mellem år og ændres. Det vil også medføre at TutorGroupLeader kan blive del af TutorGroup og gøre den kode simplere.

**Comment by Mortal** [comment]
Fixed i 569c2b220a99b5876d834714324d13ed4ea9d261 til c93c01cfea24c30ced8eed836c61dc6da97761a9
