### ISSUE TITLE
TutorGroupLeader behøver ikke 'year'

### ISSUE THREAD

**Issue by sortie** [matfystutor/web#33]
Denne værdi er allerede indeholdt ved `tutor__year` værdien (altså at en tutor allerede har et år tilknyttet).

**Comment by Mortal** [comment]
Nu hvor #20 er fikset, kan vi begynde at udfase TGL.year-feltet.

**Comment by Mortal** [comment]
Det endte med at jeg fjernede TutorGroupLeader helt. Woohoo, anarki!
