### ISSUE TITLE
Lokation på begivenheder

### ISSUE THREAD

**Issue by Sobuno** [matfystutor/web#78]
Tilføj lokation til begivenheder (hvor det er relevant, naturligvis ikke relevant for diverse deadlines), så man kan se hvor man skal være direkte i sit Calendar-feed (og på hjemmesiden) i stedet for at skulle grave mails frem.

**Comment by Mortal** [comment]
Det er i Aud. F.

**Comment by Sobuno** [comment]
Det var nu også mest sådan en enhancement issue(men jeg kan ikke få lov at smide labels på) til fremtidigt brug; har gravet min mail frem :)

**Comment by Mortal** [comment]
Fixed 984af9a..d1a1e74
